events {}

http {

    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }
    
    server {
        listen 443 ssl;
        server_name litechess.online;

        ssl_certificate     /etc/letsencrypt/live/litechess.online/fullchain.pem
        ssl_certificate_key /etc/letsencrypt/live/litechess.online/privkey.pem

        # root /usr/share/nginx/html;
        # index index.html;

        location / {
            proxy_pass http://localhost:5173;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
    }

    server {

        listen 443 ssl;
        server_name api.litechess.online;

        ssl_certificate     /etc/letsencrypt/live/litechess.online/fullchain.pem
        ssl_certificate_key /etc/letsencrypt/live/litechess.online/privkey.pem

        location / {
            proxy_pass http://localhost:8080;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /ws {
            proxy_pass http://localhost:8080;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }
    }


    server {
        listen 443 ssl;
        server_name identity.litechess.online;

        ssl_certificate     /etc/letsencrypt/live/litechess.online/fullchain.pem
        ssl_certificate_key /etc/letsencrypt/live/litechess.online/privkey.pem

         location / {
            proxy_pass http://localhost:8000;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-For $remote_addr;
         }
    }

    server {
        listen 443 ssl;
        server_name s3.localhost;

        ssl_certificate     /etc/letsencrypt/live/litechess.online/fullchain.pem
        ssl_certificate_key /etc/letsencrypt/live/litechess.online/privkey.pem

        location / {
            proxy_pass http://localhost:9000;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port 443;

            proxy_http_version 1.1;
            client_max_body_size 0;
        }
    }

    server {
        listen 443 ssl;
        server_name s3-console.litechess.online;

        ssl_certificate     /etc/letsencrypt/live/litechess.online/fullchain.pem
        ssl_certificate_key /etc/letsencrypt/live/litechess.online/privkey.pem

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;

        location / {
            proxy_pass http://localhost:9001;
        }
    }
}
